/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#F39C12",
        "on-primary": "#000000",
        background: "#000000",
        "on-background": "#e5e2e1",
        "background-light": "#f8f7f5",
        "background-dark": "#221b10",
        surface: "#19120a",
        "on-surface": "#efe0d2",
        "surface-container": "#261e16",
        "surface-container-low": "#221a12",
        "surface-container-high": "#31281f",
        "surface-dim": "#000000",
        "surface-bright": "#1a1a1a",
        outline: "#a18d7a",
        secondary: "#ffb783",
        "secondary-fixed": "#ffdcc5",
        "secondary-container": "#db7619",
        error: "#ffb4ab",
        "surface-container-lowest": "#000000",
        "outline-variant": "#534434",
        "tertiary-fixed-dim": "#4ae183",
        "primary-fixed-dim": "#ffb961",
        "on-primary-fixed": "#2b1700",
        "on-tertiary": "#003919",
        "on-tertiary-fixed": "#00210c",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#27c86e",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#301400",
        "inverse-primary": "#865300",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#004d25",
        "on-surface-variant": "#d8c3ad",
        "on-primary-container": "#603a00",
        "tertiary-fixed": "#6bfe9c",
        "primary-container": "#F39C12",
        "surface-variant": "#1a1a1a",
        "on-secondary": "#4f2500",
        "primary-fixed": "#ffddb9",
        "on-secondary-fixed-variant": "#713700",
        "on-error": "#690005",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ffb783",
        "on-secondary-container": "#451f00",
        tertiary: "#4fe586",
        "surface-tint": "#f39c12",
        "on-primary-fixed-variant": "#663e00",
        "surface-container-highest": "#1c1c1c",
        "on-tertiary-fixed-variant": "#005228",
      },
      fontFamily: {
        "data-mono": ["Orbitron", "sans-serif"],
        display: ["Orbitron", "sans-serif"],
        body: ["Orbitron", "sans-serif"],
        headline: ["Orbitron", "sans-serif"],
        "headline-lg": ["Orbitron", "sans-serif"],
        "body-sm": ["Orbitron", "sans-serif"],
        "body-lg": ["Orbitron", "sans-serif"],
        "headline-md": ["Orbitron", "sans-serif"],
        "label-caps": ["Orbitron", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["18px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["42px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        margin: "32px",
        "container-max": "1440px",
        unit: "4px",
        gutter: "16px",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
